### PR TITLE
feat: specify optimum sizes for video teasers

### PR DESCRIPTION
**Pull request by sjparkinson**
This will limit the size of the streamed videos to a 360p resolution, rather than the default of 1080p.

The lower resolution will be better for anyone on a wobbly connection.

Related changes for the video section on the front page can be found in https://github.com/Financial-Times/next-front-page/pull/2026.

### CODE REVIEW

**Comment by sjparkinson** [comment]
Spotted in on the front page today.

image

**Comment by sjparkinson** [comment]
Happy for this to become `v1.0.0-beta.13` on master?

**Comment by i-like-robots** [comment]
Yes! (the snapshot tests and changelog need updating - and yes, we need proper tests for this component!)

**Comment by i-like-robots** [comment]
v1.0.0-beta.14 is tagged for release!

**Pull request merged**
