### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by alexandercurtis**
Adds link to x-teaser documentation as suggested here https://github.com/Financial-Times/x-dash/pull/223#discussion_r275835416

Adds comment to SCSS as suggested here https://github.com/Financial-Times/x-dash/pull/223#discussion_r275838424

### CODE REVIEW

**Comment by apaleslimghost** [comment]
@alexandercurtis should the base branch be `x-teaser-timeline` not `master`?

**Comment by alexandercurtis** [comment]
@apaleslimghost oops thanks - fixed

**Comment by apaleslimghost** [comment]
we don't have to worry about the snyk thing. it's not a vulnerability that will affect us

**Comment by alexandercurtis** [comment]
@apaleslimghost Thanks for checking. It's a great help as I don't have Snyk access set up yet.

**Pull request merged**
