### PR TITLE
Add externals to styling demo

### PR DESCRIPTION
**Pull request by i-like-robots**
Squash a rollup warning

### CODE REVIEW

**Comment by i-like-robots** [comment]
Chucked this in here too before I forget https://github.com/Financial-Times/x-dash/commit/2070ea0080a077534731bb1c65f20c9b505511db

**Comment by i-like-robots** [comment]
Jest installs JSDOM and defines `window`...

**Comment by i-like-robots** [comment]
I could update the engine config?

```json
  "x-dash": {
    "engine": {
      "server": {
        "runtime": "react",
        "factory": "createElement",
        "component": "Component",
        "renderModule": "react-test-renderer",
        "render": "create"
      }
    }
  }
```

**Comment by quarterto** [comment]
could you add a `module.exports.isServer = true` to https://github.com/Financial-Times/x-dash/blob/master/packages/x-engine/src/server.js?

**Comment by i-like-robots** [comment]
Oh, um. Yes - will sneak that into another PR

**Pull request merged**
