### PR TITLE
add testURL property

### PR DESCRIPTION
**Pull request by leggsimon**
Adds the `testURL` property to the Jest config. To fix the following error with the latest version of JSDom. (Further details https://github.com/facebook/jest/issues/6766)
```
FAIL
● Test suite failed to run

SecurityError: localStorage is not available for opaque origins at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Array.forEach (<anonymous>)
```

### CODE REVIEW

**Comment by quarterto** [comment]
do we want to do it this way, or using `testEnvironment: 'node'`?

**Comment by quarterto** [comment]
actually let's do it like this but make it `https://local.ft.com` to also squash the video cors warning? i think that should work

**Comment by leggsimon** [comment]
will being `https` have bad effects? 🤔

**Comment by quarterto** [comment]
who knows!

**Comment by i-like-robots** [comment]
Hopefully JSDOM would only care about that if we were mocking location APIs etc

**Comment by i-like-robots** [comment]
For now it literally needs a URL because localstorage is not available on `about:blank` 😆

**Pull request merged**
