### PR TITLE
CPP-428 Remove files for deployed docs, deploy storybook instead

### PR DESCRIPTION
**Pull request by emortong**
Documentation has been moved to the Github Wiki https://github.com/Financial-Times/x-dash/wiki

### CODE REVIEW

**Review by apaleslimghost — DISMISSED** [review]
this looks great, nice work! the wiki looks great too, a few comments on that:

**praise**: i love the sidebar!

**suggestion (non-blocking)**: can some of the Wiki content move into the Readme instead? i'm thinking the [installation](https://github.com/Financial-Times/x-dash/wiki/Installation) and [working with x-dash](https://github.com/Financial-Times/x-dash/wiki/Working-with-x-dash) pages, that's the kind of info i'd expect to see in a readme

**question**: what's the purpose of copying the component readmes into the wiki? now they're in two places they might get out of sync

**Comment by emortong** [comment]
@apaleslimghost right! the suggestion is quite sensible, I'll make the change

and on the question, you have a good point, it will probably get out of sync, I'll make a single page linking to each component's/package's README

**Comment by emortong** [comment]
@apaleslimghost made the changes

**Review by apaleslimghost — APPROVED** [review]
looking really good, thanks!

**Pull request merged**
